---
apiVersion: v1
kind: Namespace
metadata:
  name: test1-namespace

---
apiVersion: v1
kind: Namespace
metadata:
  name: test2-namespace

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pv-admin
subjects:
- kind: Group
  name: k8s-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: oidc-test1
  namespace: test1-namespace
subjects:
- kind: Group
  name: test1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: oidc-test2
  namespace: test2-namespace
subjects:
- kind: Group
  name: test2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io