apiVersion: v1
kind: ServiceAccount
metadata:
  name: spotinst
  namespace: lab7
secrets:
- name: spotinst-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: spotinst-secret
  annotations:
    kubernetes.io/service-account.name: spotinst
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spotinst-role
rules:
# - apiGroups: [""]
#   resources: ["pods", "nodes", "replicationcontrollers", "events", "limitranges", "services","deployments","ingresses"]
#   verbs: ["get", "delete", "list", "patch", "update"]
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: spotinst-role-binding
roleRef:
  kind: ClusterRole
  name: spotinst-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: spotinst
  namespace: lab7