---
  
- name: Setup docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo 

- name: install required for docker
  shell: >
        yum install -y --setopt=obsoletes=0 \
        docker-ce-17.03.2.ce-1.el7.centos.x86_64 \
        docker-ce-selinux-17.03.2.ce-1.el7.centos.noarch

- name: register docker as a service 
  command: systemctl enable docker

- name: register docker as a service 
  command: systemctl start docker

- name: setting cgroup for docker daemon
  copy: src=daemon.json dest=/etc/docker/daemon.json

...