# https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 172.168.50.10
networking:
  podSubnet: 192.168.0.0/16
authorizationModes:
- Node
- RBAC
# controllerManagerExtraArgs:
#   kube-controller-manager:
#     horizontal-pod-autoscaler-use-rest-clients: false
# apiServerExtraArgs:
#   oidc-issuer-url: https://dex.example.com:32000
#   oidc-client-id: example-app
#   oidc-username-claim: email
#   oidc-groups-claim: groups
#   oidc-ca-file: /etc/ssh/openid-ca.pem
