apiVersion: v1
kind: Namespace
metadata:
  name: sapzil
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: sapzil


# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: admin-secret
#   namespace: sapzil
#   annotations:
#     kubernetes.io/service-account.name: admin
# type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sapzil-admin-binding
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: admin
  namespace: sapzil